# for mac os run `docker-machine ip default` to get IP to setup /etc/hosts
app:
  image: ubuntu
  stdin_open: true
  volumes:
     - "./code:/var/www/bootstrap"
nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes_from:
    - app
  volumes:
    - "./docker/nginx/bootstrap.conf:/etc/nginx/conf.d/bootstrap.conf"
  links:
    - phpfpm

phpfpm:
  image: php:7-fpm
  ports:
    - "9000:9000"
  volumes_from:
    - app
  links:
    - db
db:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: bootstrap
  volumes:
    # todo: copy it
    - "./docker/.mysql/var/lib/mysql:/var/lib/mysql"
